#!/bin/bash
#
# Converts a folder of FLAC files to ALAC files with ffmpeg

NQDIR="/tmp/flac-to-alac"
LOG_FILE="/Users/mshick/Library/Logs/flac-to-alac/info.log"
LIMIT=100

log() {
  echo "[$(date "+%Y.%m.%d %H:%M:%S")] $1" >> $LOG_FILE 2>&1
}

usage() { 
    echo "Usage: ./flac-to-alac -i infolder -o outfolder"
}

while getopts i:o: flag; do
    case "${flag}" in
        i) input="${OPTARG}" ;;
        o) output="${OPTARG}" ;;
        h) usage; exit ;;
    esac
done

if [ -z ${input+x} ] || [ -z ${output+x} ]; then
    echo "Must specify input and output folders"
    usage
    exit 1
fi

convert() {
    log "Converting $1"
    
    filename=$(basename "$1")
    filename="${filename%.*}"
    
    NQDIR=$NQDIR nq -q ffmpeg \
        -nostdin \
        -i "$input/$filename.flac" \
        -c:v copy \
        -c:a alac \
        -movflags +faststart \
        "$output/$filename.m4a"
}

log "Starting conversion of $input"

mkdir -p $NQDIR

count=0

find "$input" -name '*.flac' -print0 | 
while IFS= read -r -d '' line; do
    if [ "$count" -lt "$LIMIT" ]; then
        convert "$line"
        count=$((count + 1))
    fi
done
